media:
  input: src/assets
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/post
    view:
      fields: [ title, draft, date,tags ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: publishDate, label: publishDate, type: date }
      - { name: updatedDate, label: upateDate, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

